### Variaveis de ambiente
@baseUrl = http://localhost:3000


### Create a new user
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "email": "using-hash@example.com",
  "password": "password123"
}

### Login
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
  "email": "using-hash@example.com",
  "password": "password123"
}


### Get a user by ID
GET {{baseUrl}}/auth/3


### Get all user by email
GET {{baseUrl}}/auth?email=test@example.com

### Delete user by id
DELETE {{baseUrl}}/auth/1

### Update user
PATCH {{baseUrl}}/auth/3
Content-Type: application/json

{
  "email": "update-test@example.com",
  "password": "new-password123"
}