### Variaveis de ambiente
@baseUrl = http://localhost:3000


### Create a new user
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}

### Get a user by ID
GET {{baseUrl}}/auth/1


### Get all user by email
GET {{baseUrl}}/auth?email=test@example.com